ALTER TABLE interviews ADD COLUMN IF NOT EXISTS setup_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS profile_option VARCHAR NOT NULL DEFAULT 'upload';
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS profile_id VARCHAR;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS answers JSONB;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS feedback JSONB;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
